# Generated by Django 3.2.4 on 2021-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.CharField(max_length=1000)),
                ('risposta', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.CharField(max_length=1000)),
                ('r1', models.CharField(max_length=1000)),
                ('r2', models.CharField(max_length=1000)),
                ('r3', models.CharField(max_length=1000)),
                ('r4', models.CharField(max_length=1000)),
                ('rc', models.CharField(max_length=1000)),
            ],
        ),
    ]
