# Generated by Django 3.2.4 on 2021-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_result_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
    ]
