# Generated by Django 3.2.4 on 2021-06-21 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_storico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storico',
            old_name='result',
            new_name='score',
        ),
        migrations.AddField(
            model_name='storico',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
