# Generated by Django 3.2.4 on 2021-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210621_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images/'),
        ),
    ]
