# Generated by Django 3.2.4 on 2021-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='da',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images/'),
        ),
    ]
